version: '2'
services:
 flume:
  build: .
  ports:
   - "4000:4000"
  volumes:
   - ./delivery-agent.conf:/var/tmp/delivery-agent.conf
   - /tmp/operaciones:/var/operaciones
  environment:
   - FLUME_AGENT_NAME=server
   - FLUME_CONF_FILE=/var/tmp/delivery-agent.conf
  command:
   - ./opt/flume/bin/start-flume.sh
  expose:
   - "4000"

